const initial = {
  curStep: 1,
  question1: '',
  question2: '',
  question3: '',
  question4: '',
  question4a: '',
  question5: '',
  question5a: '',
  question5b: '',
  question5bis: '',
  question5bisa: '',
  question5bisb: '',
  question6: '',
  question7: '',
  question7a: '',
  question7b: '',
  question8: '',
  question8a: '',
  question9: '',
  question8bis: '',
  question8bisa: '',
  question9bis: '',
  question10: '',
  question10a: '',
  question10b: '',
  question11: '',
  question12: '',
  question14: '',
  question15: '',
  question16: '',
  question16a: '',
  question16b: '',
  question17: '',
  question18: '',
  question18a: '',
  question19a: '',
  question19a1: '',
  question19b: '',
  question20a: '',
  question20b: '',
  question20c: '',
  question20d: '',
  question21: '',
  question21a: '',
  question22: '',
  question22a: '',
  question22b: '',
  question22c: '',
  question23a: '',
  question23b: '',
  question24: '',
  question25: '',
  question26: '',
  question27: '',
  question27b1: '',
  question28: '',
  question28a: '',
  question29: '',
  question30: '',
  question31a: '',
  question31b: '',
  question31c: '',
  question31d: '',
  question32: '',
  question33: '',
  question34: '',
  question35: '',
  question36: '',
  question37: '',
  question38a: '',
  question38b: '',
  question38bisa: '',
  question38bisb: '',
  question38bisc: '',
  question38c: '',
  question39a: '',
  question39b: '',
  question40: '',
  question40a: '',
  question41: '',
  question42: '',
  question42bis: '',
  question43: '',
  question431: '',
  question432: '',
  question44: '',
  question45: {
    nom: '',
    nomdejeunefille: '',
    prenom: '',
    datedenaissance: '',
    nationalite: '',
  },
  question46: '',
  question47: '',
  question47a: '',
  question48: {
    portable: '',
    fixe: '',
    mail: '',
  },
  question49: {
    adresse: '',
    cp: '',
    ville: '',
    etranger: '',
  },
  question50: '',
  question51: {
    raisonsociale: '',
    cp: '',
    ville: '',
    siret: '',
    creation: '',
    taxation: '',
  },
};

const Reducer = (state = initial, action) => {
  switch (action.type) {
    case 'ANSWER':
      return { ...state, [action.question]: action.text };
    case 'SETSTEP':
      return { ...state, curStep: action.value };
    default:
      return state;
  }
};

export default Reducer;
